//  Automatically generated by the FlatBuffers compiler, do not modify.            
//  SwiftFlatBuffers, licensed under the Apache License, Version 2.0, is from FlatBuffers.            
//            
//  SwiftFlatBuffers  <https://github.com/TonyStark106/SwiftFlatBuffers>            
//

import SwiftFlatBuffers

