//  Automatically generated by the FlatBuffers compiler, do not modify.            
//  SwiftFlatBuffers, licensed under the Apache License, Version 2.0, is from FlatBuffers.            
//            
//  SwiftFlatBuffers  <https://github.com/TonyStark106/SwiftFlatBuffers>            
//

import Foundation
import SwiftFlatBuffers

public enum MyGame_OtherNameSpace_FromInclude: Int64 {

    case IncludeVal = 0

}

public final class MyGame_OtherNameSpace_Unused: FBTable {

    public final override var hardPos: FBOffset {
        return 0
    }

    public final override var hardSize: UInt {
        return 0
    }

    public final override func toFBData() -> Data {
        let temp = MyGame_OtherNameSpace_Unused()
        return temp.bbData
    }

}

extension MyGame_OtherNameSpace_Unused {

}

